package Janelas;

import BD.GerenciadorBD;
import Menu.*;

import Tipos.Compromisso;

import java.text.SimpleDateFormat;
import java.text.DateFormat;

import java.math.BigInteger;
import java.security.MessageDigest;
import javax.swing.JOptionPane;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rizzadinha
 */
public class CompromissoInserir extends javax.swing.JInternalFrame {

    /**
     * Creates new form CompromissoInserir
     */
    public CompromissoInserir() {
        initComponents();
        this.setLocation(250, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeCompromisso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldHoraCompromisso = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jDateChooserDataCompromisso = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInfoCompromisso = new javax.swing.JTextArea();
        jButtonInserirCompromisso = new javax.swing.JButton();

        setClosable(true);
        setTitle("Inserir Compromisso");

        jLabel1.setText("Nome:");

        jLabel2.setText("Hora:");

        try {
            jFormattedTextFieldHoraCompromisso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldHoraCompromisso.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("Data:");

        jLabel4.setText("Infomações:");

        jTextAreaInfoCompromisso.setColumns(20);
        jTextAreaInfoCompromisso.setLineWrap(true);
        jTextAreaInfoCompromisso.setRows(5);
        jScrollPane1.setViewportView(jTextAreaInfoCompromisso);

        jButtonInserirCompromisso.setText("Inserir");
        jButtonInserirCompromisso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirCompromissoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonInserirCompromisso)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldNomeCompromisso, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFormattedTextFieldHoraCompromisso, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDateChooserDataCompromisso, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNomeCompromisso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldHoraCompromisso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserDataCompromisso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonInserirCompromisso)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInserirCompromissoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirCompromissoActionPerformed
               
        if(jTextFieldNomeCompromisso.getText().equals("") || jTextAreaInfoCompromisso.getText().equals("") || jFormattedTextFieldHoraCompromisso.getText().equals("  :  ") || jDateChooserDataCompromisso.getDate() == null){
            JOptionPane.showMessageDialog(null, "Por favor preencha os campos");
        } 
        else{
            String nome, hora,data, info;
            Compromisso cInserir = new Compromisso();
            DateFormat dataFomatador = new SimpleDateFormat("yyyy/MM/dd");
            
            cInserir.setNome(jTextFieldNomeCompromisso.getText());
            cInserir.setHora(jFormattedTextFieldHoraCompromisso.getText());             
            cInserir.setData(dataFomatador.format(jDateChooserDataCompromisso.getDate()));  
            cInserir.setInfo(jTextAreaInfoCompromisso.getText());
            cInserir.setIdFK(AuxCompromissoUsuario.getIdUC());
                    
           GerenciadorBD.inserirCompromisso(cInserir);
       
           this.dispose();
        }
        
    }//GEN-LAST:event_jButtonInserirCompromissoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInserirCompromisso;
    private com.toedter.calendar.JDateChooser jDateChooserDataCompromisso;
    private javax.swing.JFormattedTextField jFormattedTextFieldHoraCompromisso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaInfoCompromisso;
    private javax.swing.JTextField jTextFieldNomeCompromisso;
    // End of variables declaration//GEN-END:variables
} 
