/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Janelas;

import BD.GerenciadorBD;
import BD.MD5;
import Tipos.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Rizzadinha
 */
public class UsuarioInserir extends javax.swing.JInternalFrame {

    /**
     * Creates new form UsuarioInserir
     */
    public UsuarioInserir() {
        initComponents();
        this.setLocation(300, 200);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUsuarioILogin = new javax.swing.JTextField();
        jButtonInseir = new javax.swing.JButton();
        jTextFieldUsuarioISenha = new javax.swing.JPasswordField();
        jTextFieldUsuarioISenha2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Inserir Usuario");

        jLabel1.setText("Login:");

        jLabel2.setText("Senha:");

        jButtonInseir.setText("Inserir");
        jButtonInseir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInseirActionPerformed(evt);
            }
        });

        jLabel3.setText("Novamente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldUsuarioISenha))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldUsuarioILogin, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUsuarioISenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInseir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldUsuarioILogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldUsuarioISenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUsuarioISenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jButtonInseir)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInseirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInseirActionPerformed
              
      if(jTextFieldUsuarioILogin.getText().equals("") || jTextFieldUsuarioISenha.getText().equals("") || jTextFieldUsuarioISenha2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor preencha os campos");
        }  
      else{ 
        if(GerenciadorBD.checkExistente(jTextFieldUsuarioILogin.getText())){
            JOptionPane.showMessageDialog(null, "Usuario Existente");
        }
        else if(jTextFieldUsuarioISenha.getText().equals(jTextFieldUsuarioISenha2.getText())){
          Usuario uInserir = new Usuario();
          uInserir.setLogin(jTextFieldUsuarioILogin.getText());
          uInserir.setSenha(MD5.md5Hash(jTextFieldUsuarioISenha.getText()));
          System.out.println("senha: " + uInserir.getSenha());

          GerenciadorBD.inserirUusuario(uInserir);
          this.dispose();
        }     
        else{
            JOptionPane.showMessageDialog(null, "Senhas não conferem"); 
        }
        
      }
      
    }//GEN-LAST:event_jButtonInseirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInseir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldUsuarioILogin;
    private javax.swing.JPasswordField jTextFieldUsuarioISenha;
    private javax.swing.JPasswordField jTextFieldUsuarioISenha2;
    // End of variables declaration//GEN-END:variables
}
