package Menu;



import Janelas.*;

import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rizzadinha
 */
public class MenuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuJFrame
     */
    public MenuJFrame() {
        
        initComponents();
        
        Login telaLogin = new Login();
        
        jDesktopPane.add(telaLogin);
        
        telaLogin.show();
              
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCompromissos = new javax.swing.JMenu();
        jMenuItemCInserir = new javax.swing.JMenuItem();
        jMenuItemCAlterar = new javax.swing.JMenuItem();
        jMenuItemCRemover = new javax.swing.JMenuItem();
        jMenuItemCRelatorios = new javax.swing.JMenuItem();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemUInserir = new javax.swing.JMenuItem();
        jMenuItemUAlterar = new javax.swing.JMenuItem();
        jMenuItemURemover = new javax.swing.JMenuItem();
        jMenuItemURelatorios = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemAInformacoes = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemLogar = new javax.swing.JMenuItem();
        jMenuItemDeslogin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda de Compromissos");

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        jMenuCompromissos.setText("Compromissos");

        jMenuItemCInserir.setText("Inserir");
        jMenuItemCInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCInserirActionPerformed(evt);
            }
        });
        jMenuCompromissos.add(jMenuItemCInserir);

        jMenuItemCAlterar.setText("Alterar");
        jMenuItemCAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCAlterarActionPerformed(evt);
            }
        });
        jMenuCompromissos.add(jMenuItemCAlterar);

        jMenuItemCRemover.setText("Remover");
        jMenuItemCRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCRemoverActionPerformed(evt);
            }
        });
        jMenuCompromissos.add(jMenuItemCRemover);

        jMenuItemCRelatorios.setText("Relatórios");
        jMenuItemCRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCRelatoriosActionPerformed(evt);
            }
        });
        jMenuCompromissos.add(jMenuItemCRelatorios);

        jMenuBar1.add(jMenuCompromissos);

        jMenuUsuarios.setText("Usuários");

        jMenuItemUInserir.setText("Inserir");
        jMenuItemUInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUInserirActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemUInserir);

        jMenuItemUAlterar.setText("Alterar");
        jMenuItemUAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUAlterarActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemUAlterar);

        jMenuItemURemover.setText("Remover");
        jMenuItemURemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemURemoverActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemURemover);

        jMenuItemURelatorios.setText("Relatórios");
        jMenuItemURelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemURelatoriosActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemURelatorios);

        jMenuBar1.add(jMenuUsuarios);

        jMenuAjuda.setText("Ajuda");

        jMenuItemAInformacoes.setText("Informações");
        jMenuItemAInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAInformacoesActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemAInformacoes);

        jMenuBar1.add(jMenuAjuda);

        jMenu1.setText("Logar/Deslogar");

        jMenuItemLogar.setText("Logar");
        jMenuItemLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLogar);

        jMenuItemDeslogin.setText("Deslogar");
        jMenuItemDeslogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDesloginActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDeslogin);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCInserirActionPerformed
        
       if(AuxCompromissoUsuario.getValida()==1){
        
            CompromissoInserir telaInserirC = new CompromissoInserir();
        
            jDesktopPane.add(telaInserirC);
        
            telaInserirC.show();
       }
       else{
       JOptionPane.showMessageDialog(null, "Necessário logar");
       }
       
    }//GEN-LAST:event_jMenuItemCInserirActionPerformed

    private void jMenuItemCAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCAlterarActionPerformed
        
        if(AuxCompromissoUsuario.getValida()==1){
        
            CompromissoAlterar telaAlterarC = new CompromissoAlterar();
        
            jDesktopPane.add(telaAlterarC);
        
            telaAlterarC.show();
        }
        else{
        JOptionPane.showMessageDialog(null, "Necessário logar");
        }
        
    }//GEN-LAST:event_jMenuItemCAlterarActionPerformed

    private void jMenuItemCRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCRemoverActionPerformed
        
        if(AuxCompromissoUsuario.getValida()==1){
        
            CompromissoRemover telaRemoverC = new CompromissoRemover();
        
            jDesktopPane.add(telaRemoverC);
        
            telaRemoverC.show();    
        }
        else{
        JOptionPane.showMessageDialog(null, "Necessário logar");
        }
        
    }//GEN-LAST:event_jMenuItemCRemoverActionPerformed

    private void jMenuItemCRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCRelatoriosActionPerformed
        
        if(AuxCompromissoUsuario.getValida()==1){
        
            CompromissoListar telaListarC = new CompromissoListar();
        
            jDesktopPane.add(telaListarC);
             
            telaListarC.show();
            
        }
        else{
        JOptionPane.showMessageDialog(null, "Necessário logar");
        }   
            
    }//GEN-LAST:event_jMenuItemCRelatoriosActionPerformed

    private void jMenuItemLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogarActionPerformed
        
        if(AuxCompromissoUsuario.getValida() == 1){
            JOptionPane.showMessageDialog(null, "Já esta Logado");
        }
        else{
          
            Login telaLogin = new Login();
        
            jDesktopPane.add(telaLogin);
        
            telaLogin.show();
        }
    }//GEN-LAST:event_jMenuItemLogarActionPerformed

    private void jMenuItemDesloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDesloginActionPerformed
        
        AuxCompromissoUsuario.setValida(0);
        jDesktopPane.removeAll(); 
        jDesktopPane.show(false);
        jDesktopPane.show(true);
        JOptionPane.showMessageDialog(null, "Deslogado com Sucesso");
        
    }//GEN-LAST:event_jMenuItemDesloginActionPerformed

    private void jMenuItemUInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUInserirActionPerformed
        
        UsuarioInserir telaInseir = new UsuarioInserir();
        
        jDesktopPane.add(telaInseir);
        
        telaInseir.show();
        
    }//GEN-LAST:event_jMenuItemUInserirActionPerformed

    private void jMenuItemUAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUAlterarActionPerformed
        
        if(AuxCompromissoUsuario.getValida()==1){
        
            UsuarioAlterar telaAlterar = new UsuarioAlterar();
        
            jDesktopPane.add(telaAlterar);
        
            telaAlterar.show();
        }
        else{
        JOptionPane.showMessageDialog(null, "Necessário logar");
        }  
        
        
    }//GEN-LAST:event_jMenuItemUAlterarActionPerformed

    private void jMenuItemURemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemURemoverActionPerformed
        
        if(AuxCompromissoUsuario.getValida()==1){
        
            UsuarioRemover telaRemover = new UsuarioRemover();
        
            jDesktopPane.add(telaRemover);
        
            telaRemover.show();
            
        }
        else{
        JOptionPane.showMessageDialog(null, "Necessário logar");
        } 
        
    }//GEN-LAST:event_jMenuItemURemoverActionPerformed

    private void jMenuItemURelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemURelatoriosActionPerformed
        
        if(AuxCompromissoUsuario.getValida()==1){
        
            UsuarioListar telaListar = new UsuarioListar();
        
            jDesktopPane.add(telaListar);
        
            telaListar.show();
            
            
        }
        else{
        JOptionPane.showMessageDialog(null, "Necessário logar");
        } 
        
    }//GEN-LAST:event_jMenuItemURelatoriosActionPerformed

    private void jMenuItemAInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAInformacoesActionPerformed
        // TODO add your handling code here:
        AjudaInformacoes informacoes = new AjudaInformacoes();
        
        jDesktopPane.add(informacoes);
        
        informacoes.show();
    }//GEN-LAST:event_jMenuItemAInformacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCompromissos;
    private javax.swing.JMenuItem jMenuItemAInformacoes;
    private javax.swing.JMenuItem jMenuItemCAlterar;
    private javax.swing.JMenuItem jMenuItemCInserir;
    private javax.swing.JMenuItem jMenuItemCRelatorios;
    private javax.swing.JMenuItem jMenuItemCRemover;
    private javax.swing.JMenuItem jMenuItemDeslogin;
    private javax.swing.JMenuItem jMenuItemLogar;
    private javax.swing.JMenuItem jMenuItemUAlterar;
    private javax.swing.JMenuItem jMenuItemUInserir;
    private javax.swing.JMenuItem jMenuItemURelatorios;
    private javax.swing.JMenuItem jMenuItemURemover;
    private javax.swing.JMenu jMenuUsuarios;
    // End of variables declaration//GEN-END:variables
}
